# -*- coding: utf-8 -*-
"""hangman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LX5fs7NRvtpuwTNKmWk8SpzUi19uXSaV
"""

import random

words = ["python", "laptop", "network", "gaming", "teacher"]

secret_word = random.choice(words)

guessed_letters = []

max_attempts = 6
wrong_guesses = 0

print("🎮 Welcome to Hangman Game!")
print("Guess the word one letter at a time.")
print("You have 6 incorrect guesses.\n")

while wrong_guesses < max_attempts:

    display_word = ""

    for letter in secret_word:
        if letter in guessed_letters:
            display_word += letter + " "
        else:
            display_word += "_ "

    print("Word:", display_word)

    if "_" not in display_word:
        print("\n🎉 Congratulations! You guessed the word:", secret_word)
        break

    guess = input("Enter a letter: ").lower()

    if len(guess) != 1 or not guess.isalpha():
        print("⚠️ Please enter only one alphabet letter.\n")
        continue

    if guess in guessed_letters:
        print("⚠️ You already guessed that letter.\n")
        continue

    guessed_letters.append(guess)

    if guess in secret_word:
        print("✅ Correct guess!\n")
    else:
        wrong_guesses += 1
        remaining = max_attempts - wrong_guesses
        print("❌ Wrong guess!")
        print("Remaining attempts:", remaining, "\n")

if wrong_guesses == max_attempts:
    print("💀 Game Over!")
    print("The correct word was:", secret_word)